app:
  resource: '@AppBundle/Controller/'
  type: annotation

redirect:
  path: /{uri}
  defaults: { _controller: AppBundle:Default:redirect }
  requirements:
    urlId: '\d{12}'

cutter-main:
  path: /cutter-url/
  defaults: { _controller: AppBundle:CutterUrl:index }

cutter-test:
  path: /api/test
  defaults: { _controller: AppBundle:CutterUrl:test }
  requirements:
    _format: json
    methods: POST

cutter-info:
  path: /cutter-url/info/
  defaults: { _controller: AppBundle:CutterUrl:info }

cutter-info-each:
  path: /cutter-url/info/{urlId}
  defaults: { _controller: AppBundle:CutterUrl:infoEach, urlId: 0 }
  requirements:
    urlId: '\d+'

cutter-save:
  path:  /cutter-url/save-url
  defaults: { _controller: AppBundle:CutterUrl:saveUrl }
